# Request
uint16 goal_x
uint8 goal_y
int16 goal_angle
---
# Result
uint16 final_x
uint8 final_y
int16 final_angle
---
# Feedback
uint16 robot_x
uint8 robot_y
int16 robot_angle
uint16 distance_to_goal
int16 angle_difference
